-- Create mission_content table
CREATE TABLE IF NOT EXISTS mission_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create RLS policies
ALTER TABLE mission_content ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to view mission content
CREATE POLICY "Allow anonymous users to view mission content"
    ON mission_content
    FOR SELECT
    TO authenticated, anon
    USING (true);

-- Allow authenticated users to manage mission content
CREATE POLICY "Allow authenticated users to manage mission content"
    ON mission_content
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
