-- Create team_members table
CREATE TABLE IF NOT EXISTS team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    image_src TEXT NOT NULL,
    bio TEXT NOT NULL,
    linkedin_url TEXT,
    twitter_url TEXT,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Create trigger to update the updated_at timestamp
CREATE TRIGGER set_timestamp
    BEFORE UPDATE ON team_members
    FOR EACH ROW
    EXECUTE PROCEDURE trigger_set_timestamp();

-- Insert initial data
INSERT INTO team_members (name, position, image_src, bio, linkedin_url, twitter_url, display_order) VALUES
(
    'Dr. Jane Smith',
    'Founder & Chief Nutritionist',
    '/placeholder.svg?height=200&width=200&text=Jane',
    'With over 15 years of experience in nutrition and wellness, Dr. Smith leads our team with innovative approaches to personalized nutrition.',
    'https://linkedin.com',
    'https://twitter.com',
    1
),
(
    'John Doe',
    'Senior Dietitian',
    '/placeholder.svg?height=200&width=200&text=John',
    'Specializing in sports nutrition and performance optimization, John brings expertise in creating customized meal plans for athletes.',
    'https://linkedin.com',
    'https://twitter.com',
    2
),
(
    'Emily Brown',
    'Nutrition Coach',
    '/placeholder.svg?height=200&width=200&text=Emily',
    'Emily''s passion for holistic wellness and behavioral change helps clients develop sustainable healthy eating habits.',
    'https://linkedin.com',
    'https://twitter.com',
    3
);
