-- Create plugins table
CREATE TABLE IF NOT EXISTS plugins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    script TEXT NOT NULL,
    enabled BOOLEAN DEFAULT true,
    order_number INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comment to the table
COMMENT ON TABLE plugins IS 'Stores website plugins and scripts';

-- Add comments to the columns
COMMENT ON COLUMN plugins.name IS 'Name of the plugin';
COMMENT ON COLUMN plugins.script IS 'The script/code of the plugin';
COMMENT ON COLUMN plugins.enabled IS 'Whether the plugin is currently enabled';
COMMENT ON COLUMN plugins.order_number IS 'Order in which the plugin should be loaded';

-- Create trigger for updating updated_at timestamp
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON plugins
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
