-- Create whatsapp_settings table
CREATE TABLE IF NOT EXISTS whatsapp_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL,
    message TEXT DEFAULT 'Hello! I''m interested in your services.',
    position VARCHAR(20) DEFAULT 'bottom-right',
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comment to the table
COMMENT ON TABLE whatsapp_settings IS 'Stores WhatsApp button configuration';

-- Add comments to the columns
COMMENT ON COLUMN whatsapp_settings.phone_number IS 'WhatsApp phone number with country code';
COMMENT ON COLUMN whatsapp_settings.message IS 'Default message to be sent';
COMMENT ON COLUMN whatsapp_settings.position IS 'Button position on screen (bottom-right, bottom-left, top-right, top-left)';
COMMENT ON COLUMN whatsapp_settings.enabled IS 'Whether the WhatsApp button is enabled';

-- Create trigger for updating updated_at timestamp
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON whatsapp_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default settings
INSERT INTO whatsapp_settings (phone_number, message, position, enabled)
VALUES ('254700000000', 'Hello! I''m interested in your services.', 'bottom-right', true)
ON CONFLICT DO NOTHING;
