-- Create tawkto_settings table
CREATE TABLE IF NOT EXISTS tawkto_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id VARCHAR(100) NOT NULL,
    widget_id VARCHAR(100) NOT NULL,
    enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add comment to the table
COMMENT ON TABLE tawkto_settings IS 'Stores Tawk.to integration settings';

-- Add comments to the columns
COMMENT ON COLUMN tawkto_settings.property_id IS 'Tawk.to Property ID';
COMMENT ON COLUMN tawkto_settings.widget_id IS 'Tawk.to Widget ID';
COMMENT ON COLUMN tawkto_settings.enabled IS 'Whether the Tawk.to widget is enabled';

-- Create trigger for updating updated_at timestamp
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON tawkto_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default settings (disabled by default until proper IDs are set)
INSERT INTO tawkto_settings (property_id, widget_id, enabled)
VALUES ('your-property-id', 'your-widget-id', false)
ON CONFLICT DO NOTHING;
