-- Create the smartspoon_steps_settings table
CREATE TABLE IF NOT EXISTS public.smartspoon_steps_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  background_image TEXT,
  title TEXT DEFAULT 'Step by step to get started',
  subtitle TEXT DEFAULT 'FAST SOLUTION',
  description TEXT DEFAULT 'Get started with our easy-to-follow process. We''ve simplified nutrition management into four straightforward steps to help you achieve your health goals.',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.smartspoon_steps_settings ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow authenticated users to select steps settings" 
  ON public.smartspoon_steps_settings 
  FOR SELECT 
  TO authenticated 
  USING (true);

CREATE POLICY "Allow authenticated users to insert steps settings" 
  ON public.smartspoon_steps_settings 
  FOR INSERT 
  TO authenticated 
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update steps settings" 
  ON public.smartspoon_steps_settings 
  FOR UPDATE 
  TO authenticated 
  USING (true);

-- Create policies for anonymous users to view
CREATE POLICY "Allow anonymous users to select steps settings" 
  ON public.smartspoon_steps_settings 
  FOR SELECT 
  TO anon 
  USING (true);

-- Add realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.smartspoon_steps_settings;
