-- Create the smartspoon_packages_settings table
CREATE TABLE IF NOT EXISTS public.smartspoon_packages_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT DEFAULT 'Choose the Right Plan for Your Practice',
  subtitle TEXT DEFAULT 'PRICING PLANS',
  description TEXT DEFAULT 'Select from our range of flexible pricing options designed to meet the needs of nutrition professionals at every stage of their practice.',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.smartspoon_packages_settings ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow authenticated users to select packages settings" 
  ON public.smartspoon_packages_settings 
  FOR SELECT 
  TO authenticated 
  USING (true);

CREATE POLICY "Allow authenticated users to insert packages settings" 
  ON public.smartspoon_packages_settings 
  FOR INSERT 
  TO authenticated 
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update packages settings" 
  ON public.smartspoon_packages_settings 
  FOR UPDATE 
  TO authenticated 
  USING (true);

-- Create policies for anonymous users to view
CREATE POLICY "Allow anonymous users to select packages settings" 
  ON public.smartspoon_packages_settings 
  FOR SELECT 
  TO anon 
  USING (true);

-- Add realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.smartspoon_packages_settings;
